name: Windows Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Download vc32tools
      run: |
        git clone https://github.com/gildor2/BuildTools.git
    - name: Build the project
      run: |
        $env:PATH += ";$($pwd.Path)/BuildTools/bin"
        sh build.sh
    - name: Add artifact
      uses: actions/upload-artifact@v4
      with:
        name: umodel-windows-${{ github.sha }}
        path: umodel.exe